Instance test server (#5)
* Moved test server to use module instances.
First attempt.

* Added a test stub
Made server tests to pass
Created a docker image for the test server

* Fixed a lot of tests
9 still failing

* Got all the integration tests passing.
Kept all argument mapping methods + endpoint for former test runner

* some Review comments changes

* file renaming

* Auto stash before merge of "instance-test-server" and "origin/instance-test-server"

Rename the test stub to follow other SDK module naming convention

* Too recent typescript version (i.e. > 2.7) blocks "npm run gulp" from working: 
@dojo/core/Evented.d.ts(32,95): error TS2
error TS2344: Type 'M[keyof M]' does not satisfy the constraint 'EventObject<keyof M>'. dojo

* Typescripting everything

* Server now passes all integration tests

* Added a step to circle CI for building the test server

* Stopped quitting on CTRL-C

* Update package.json

* experiments

* Fix for windows

* Normalised some path

* Fix to point to the correct map file

* Fixed source mapping errors.

Coverage reports seem now correct

* Review comments
Docker image fix

* Added unit test step in docker image

The code coverage seems to work and is now defined and managed in a separate file i.e. codeCoverage.js (still in Javascript because I did not manage to get it working in typescript). The code of the old server and corresponding mapping has been left unchanged but will be removed after Circle CI is changed to use the instance server testrunner instead of the former one. This will happen after this branch gets merged to master. Currently, tests are failing in integration lab but this is not due to the test server. In production, all tests pass apart from "execute resource" because we currently do not have any writable resources.
Since we need urgently the instance server to be implemented so that Javascript SDK can be fully tested and released on Friday, the decision has been taken to merge this branch. Any other review comments will be taken into account as part of a separate pull request if any.